/* FARHAN PORTFOLIO — main.js */
(function(){'use strict';
var SKILLS=[['HTML',96],['CSS',93],['JavaScript',90],['TypeScript',85],['Python',87],['Prompt Engineering',94],['N8N',86],['Zapier',88],['Modern Python Web Dev',84],['Web Development',92],['API Integration',90],['AI Chatbot Development',89],['Full Stack Development',86],['Backend Development',85],['Frontend Development',90],['Next.js',90],['Git',90],['Workflows',90],['AI Developer',90],['Problem Solving',90],['GitHub Deployment',90]];
var $=function(s,c){return(c||document).querySelector(s)},$$=function(s,c){return[].slice.call((c||document).querySelectorAll(s))};
function esc(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;')}
function repairSections(){var main=$('main'),projects=$('#projects'),grid=$('#projectsGrid');if(!main||!projects||!grid)return;var sections=$$('section[id]',grid);sections.forEach(function(section){main.insertBefore(section,projects.nextElementSibling)});grid.setAttribute('data-repaired','true')}
function preloader(){var p=$('#preloader');if(!p)return;var done=function(){p.classList.add('done');p.style.pointerEvents='none'};setTimeout(done,1200);window.addEventListener('load',done)}
function header(){var h=$('#header'),t=$('#navToggle'),m=$('#navMenu');if(h)window.addEventListener('scroll',function(){h.classList.toggle('scrolled',scrollY>40)},{passive:true});if(!t||!m)return;t.onclick=function(){var o=m.classList.toggle('open');t.classList.toggle('open',o);t.setAttribute('aria-expanded',o)};$$('.nav-link',m).forEach(function(a){a.onclick=function(){m.classList.remove('open');t.classList.remove('open')}})}
function navigation(){var links=$$('a[href^="#"]');links.forEach(function(a){a.addEventListener('click',function(e){var id=a.getAttribute('href');if(!id||id==='#')return;var target=$(id);if(!target)return;e.preventDefault();var header=$('#header'),offset=(header?header.offsetHeight:72)+12,y=target.getBoundingClientRect().top+window.pageYOffset-offset;window.scrollTo({top:Math.max(0,y),behavior:'smooth'});history.replaceState(null,'',id)})})}
function scrollspy(){var sections=$$('main section[id]'),links=$$('.nav-link[href^="#"]');if(!sections.length||!links.length)return;function setActive(id){links.forEach(function(a){a.classList.toggle('active',a.getAttribute('href')==='#'+id)})}function update(){var point=window.scrollY+(window.innerHeight*0.32),current=sections[0].id;sections.forEach(function(s){if(s.offsetTop<=point)current=s.id});setActive(current)}window.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update);update()}
function typing(){var x=$('#typedText'),l=$('#revealLine');if(!x||!l)return;var full='Hi, I am Farhan. I am 30 years old.';x.textContent='';var i=0;function go(){if(i>=full.length){l.classList.add('show');return}x.textContent=full.slice(0,++i);setTimeout(go,35)}go()}
function profileImage(){var hero=$('.hero-inner'),badge=$('.hero-badge',hero);if(!hero||!badge||$('.hero-profile',hero))return;var wrap=document.createElement('div');wrap.className='hero-profile';wrap.innerHTML='<img src="https://i.ibb.co/jcWYBQ2/farhan-fiver-profile-pic.png" alt="Farhan Ahmed profile photo" loading="eager">';var style=document.createElement('style');style.textContent='.hero-profile{display:flex;justify-content:center;margin:0 0 28px}.hero-profile img{width:150px;height:150px;object-fit:cover;border-radius:50%;border:3px solid rgba(34,211,238,.75);box-shadow:0 0 0 8px rgba(139,92,246,.10),0 18px 55px rgba(34,211,238,.22);background:#0c1322}.hero-profile img:hover{transform:translateY(-3px);transition:transform .25s ease}@media(max-width:600px){.hero-profile img{width:120px;height:120px}}';document.head.appendChild(style);hero.insertBefore(wrap,badge)}
function reveal(){var e=$$('.reveal');if(!('IntersectionObserver'in window)){e.forEach(function(x){x.classList.add('visible')});return}var io=new IntersectionObserver(function(a){a.forEach(function(x){if(x.isIntersecting){x.target.classList.add('visible');io.unobserve(x.target)}})},{threshold:.08});e.forEach(function(x){io.observe(x)})}
function skills(){var g=$('#skillsGrid');if(!g)return;g.innerHTML='';SKILLS.forEach(function(s){var e=document.createElement('div');e.className='skill-item visible';e.innerHTML='<div class="skill-head"><span class="skill-name"><span class="skill-dot"></span>'+esc(s[0])+'</span><span class="skill-level">'+s[1]+'%</span></div><div class="skill-bar"><span class="skill-bar-fill" style="width:'+s[1]+'%"></span></div>';g.appendChild(e)})}
function projects(){var g=$('#projectsGrid');if(!g||typeof PROJECTS==='undefined')return;g.innerHTML='';PROJECTS.forEach(function(p){var e=document.createElement('article');e.className='project-card reveal visible';e.setAttribute('tabindex','0');e.setAttribute('role','button');e.setAttribute('aria-label','Open details for '+p.title);e.innerHTML='<div class="project-image-wrap"><img class="project-image" src="'+esc(p.image)+'" alt="'+esc(p.title)+'" loading="lazy"><div class="project-overlay"><span>View project ↗</span></div></div><div class="project-body"><h3>'+esc(p.title)+'</h3><p>'+esc(p.description)+'</p><div class="project-tags">'+(p.tags||[]).map(function(t){return'<span class="project-tag">'+esc(t)+'</span>'}).join('')+'</div></div>';e.addEventListener('click',function(){openProject(p)});e.addEventListener('keydown',function(ev){if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();openProject(p)}});g.appendChild(e)})}
function openProject(p){var m=$('#projectModal'),img=$('#modalImage'),title=$('#modalTitle'),desc=$('#modalDesc'),tags=$('#modalTags');if(!m)return;if(img){img.src=p.image;img.alt=p.title}if(title)title.textContent=p.title;if(desc)desc.textContent=p.longDescription||p.description;if(tags)tags.innerHTML=(p.tags||[]).map(function(t){return'<span class="project-tag">'+esc(t)+'</span>'}).join('');m.hidden=false;m.classList.add('open');document.body.classList.add('modal-open')}
function contact(){var f=$('#contactForm');if(!f)return;var n=$('#contactName'),em=$('#contactEmail'),m=$('#contactMessage'),b=$('#contactSubmit'),st=$('#formStatus');f.onsubmit=function(e){e.preventDefault();if(!n.value.trim()||!em.value.trim()||!m.value.trim())return;b.disabled=true;st.textContent='Sending...';var d=new FormData(f);d.set('access_key','99b9c475-6d69-4d35-b369-4934590623c4');d.set('subject','New Portfolio Contact Message');fetch('https://api.web3forms.com/submit',{method:'POST',body:d,headers:{Accept:'application/json'}}).then(function(r){return r.json()}).then(function(j){if(!j.success)throw Error(j.message||'Message could not be sent');f.reset();st.textContent='✓ Message sent! I will get back to you soon.';st.className='form-status success'}).catch(function(e){st.textContent='✗ '+e.message;st.className='form-status error'}).finally(function(){b.disabled=false})}}
function modal(){var m=$('#projectModal');if(!m)return;var close=function(){m.classList.remove('open');m.hidden=true;document.body.classList.remove('modal-open')};var c=$('.modal-close',m),b=$('.modal-backdrop',m),ca=$('#modalCloseAlt');if(c)c.onclick=close;if(b)b.onclick=close;if(ca)ca.onclick=close;document.addEventListener('keydown',function(e){if(e.key==='Escape'&&!m.hidden)close()})}
function marquee(){var t=$('.marquee-track');if(t)t.innerHTML+=t.innerHTML}
function boot(){repairSections();preloader();header();navigation();scrollspy();profileImage();typing();skills();projects();contact();modal();marquee();setTimeout(reveal,50)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
