const PROJECTS = [
{title:"AI Chatbot Assistant",description:"A conversational AI assistant built with prompt engineering and a clean responsive chat interface for context-aware conversations.",longDescription:"A practical AI chatbot project using structured prompting, context handling and a modern responsive chat interface.",image:"assets/project-ai.svg",tags:["AI","Chatbot","Prompt Engineering","JavaScript"]},
{title:"AI Quiz Game",description:"An interactive quiz game with questions, answer selection, score tracking and a polished learning-focused interface.",longDescription:"A browser quiz application designed for engaging learning with interactive questions, scoring and responsive UI.",image:"assets/project-quiz.svg",tags:["JavaScript","Quiz","UI/UX","Web Development"]},
{title:"Currency Exchange App",description:"A currency conversion application supporting 25 currencies with a simple responsive interface for quick exchange calculations.",longDescription:"A practical currency exchange project for selecting currencies and calculating conversions through a clean user interface.",image:"assets/project-python.svg",tags:["Python","Currency API","Streamlit","API Integration"]},
{title:"PDF Generator",description:"A Python PDF generation tool that creates clean downloadable documents from user-provided information.",longDescription:"A utility project for generating structured PDF documents programmatically with clean formatting and reliable file generation.",image:"assets/project-content.svg",tags:["Python","PDF","Automation","File Generation"]},
{title:"Airplane Ticket Registration System",description:"A ticket registration application for passenger information and flight booking details with a simple user-friendly workflow.",longDescription:"A practical registration project demonstrating form handling, validation, structured data and a flight booking workflow.",image:"assets/project-airplane.svg",tags:["Python","Forms","Data Management","UI"]},
{title:"Real-Time Up & Down Report",description:"A reporting dashboard that presents changing values and performance information with clear visual up/down indicators.",longDescription:"A dashboard-style project focused on monitoring changing values and presenting movement clearly through status indicators and reports.",image:"assets/project-report.svg",tags:["Python","Dashboard","Reports","Data Visualization"]},
{title:"Super Collection — E-Commerce Store",description:"A premium Pakistani fashion e-commerce experience with products, authentication, cart management, orders and Firebase integration.",longDescription:"A modern shopping experience with product browsing, authentication, cart management, order history and Firebase-backed data handling.",image:"assets/project-ecommerce.svg",tags:["React","Firebase","E-Commerce","JavaScript"]},
{title:"Personal AI Engineer Portfolio",description:"A responsive portfolio showcasing AI engineering, web development, automation skills, projects and professional contact links.",longDescription:"A responsive animated portfolio with project cards, skills, social links, contact form, smooth navigation and GitHub Pages deployment.",image:"assets/project-portfolio.svg",tags:["HTML","CSS","JavaScript","GitHub Pages"]},
{title:"n8n AI Workflow Automation",description:"AI-powered workflow automation connecting apps, APIs and business processes to reduce repetitive manual work.",longDescription:"Automation workflows built with n8n, APIs and AI services to connect repetitive tasks into structured automated pipelines.",image:"assets/project-n8n.svg",tags:["n8n","AI Automation","APIs","Workflows"]},
{title:"Zapier Business Automation",description:"Multi-step Zapier automation workflows connecting apps, triggers and actions to streamline repetitive business tasks.",longDescription:"A workflow automation project focused on connecting services through triggers, actions and API-based steps for reliable task automation.",image:"assets/project-zapier.svg",tags:["Zapier","Automation","APIs","Workflows"]},
{title:"AI Document Summarizer",description:"An AI-powered document tool that turns lengthy text into concise, structured summaries for faster reading and review.",longDescription:"A practical AI productivity project focused on extracting key information from long documents and presenting it as clear, concise summaries.",image:"assets/project-document.svg",tags:["AI","Python","NLP","Automation"]},
{title:"Smart Contact & Lead Automation",description:"An automated lead workflow that captures contact information, organizes submissions and connects follow-up actions through automation.",longDescription:"A business automation workflow designed to capture leads, structure incoming data and trigger useful follow-up actions using APIs and workflow tools.",image:"assets/project-leads.svg",tags:["n8n","Automation","APIs","Lead Management"]}
];

document.addEventListener('DOMContentLoaded',function(){var s=document.createElement('style');s.textContent='body.modal-open{overflow:hidden}.project-modal{position:fixed!important;inset:0!important;z-index:9999!important;display:flex!important;align-items:center!important;justify-content:center!important;padding:24px!important;overflow:auto!important}.project-modal[hidden]{display:none!important}.project-modal .modal-backdrop{position:absolute!important;inset:0!important;background:rgba(2,6,15,.8)!important;backdrop-filter:blur(12px)!important;-webkit-backdrop-filter:blur(12px)!important}.project-modal .modal-dialog{position:relative!important;z-index:2!important;width:min(760px,94vw)!important;max-height:86vh!important;overflow:auto!important;margin:auto!important;padding:28px!important;border:1px solid rgba(255,255,255,.14)!important;border-radius:24px!important;background:linear-gradient(145deg,rgba(15,23,42,.97),rgba(7,11,20,.98))!important;box-shadow:0 30px 100px rgba(0,0,0,.65),0 0 50px rgba(34,211,238,.1)!important}.project-modal .modal-dialog img{width:100%!important;max-height:330px!important;object-fit:cover!important;border-radius:16px!important;margin-bottom:22px!important}.project-modal .modal-close{position:absolute!important;right:16px!important;top:14px!important;z-index:3!important;width:42px!important;height:42px!important;border-radius:50%!important;background:rgba(7,11,20,.8)!important;border:1px solid rgba(255,255,255,.14)!important;font-size:28px!important;line-height:1!important}.project-modal .modal-dialog h3{font-size:clamp(1.5rem,3vw,2rem)!important;margin-bottom:10px!important}.project-modal .modal-dialog p{color:#9aa7bd!important;margin-bottom:18px!important}#modalTags{display:flex!important;flex-wrap:wrap!important;gap:8px!important;margin-bottom:22px!important}@media(max-width:600px){.project-modal{padding:12px!important}.project-modal .modal-dialog{padding:20px!important;border-radius:18px!important;max-height:90vh!important}.project-modal .modal-dialog img{max-height:220px!important}}';document.head.appendChild(s)});
